git :
 depth : 5

stages :
 - "Build and Test"
 - "Package"
 
jobs :
 include :
 - stage : "Build and Test"
   language : java
   jdk : oraclejdk11
   before_script :
    - cd sample-application-backend
   script :
    - mvn clean verify
 - stage : "Build and Test"
   language : node.js
   node_js : "12.20"
   before_script :
    - cd sample-application-frontend
   script :
    - npm install 
    - npm build
 - stage : "Package"
   before_script :
    - cd sample-application-backend
   script :
    - docker build -t nasirc/backend .
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker push nasirc/backend
 - stage : "Package"
   before_script :
    - cd sample-application-frontend
   script :
    - docker build -t nasirc/frontend .
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker push nasirc/frontend

cache :
 directories :
  - "$HOME/.m2/repository"
  - "$HOME/.npm"

services :
 - docker
