git :
 depth : 5

stages :
 - "Build and Test"
 - "Package"
 
jobs :
 include :
 - stage : "Build and Test"
   language : java
   jdk : oraclejdk11
   before_script :
    - cd sample-application-backend
   script :
   - echo "Maven build"
   - echo "Run test coverage and Quality Gate"
 - stage : "Build and Test"
   language : node.js
   node_js : "12.20"
   before_script :
    - cd sample-application-frontend
   script :
    - echo "NPM install and build"
 - stage : "Package"
   before_script :
    - cd sample-application-backend
   script :
    - echo "Docker build ..."
    - bash docker build -t vvalette/backend .
    - echo "Docker login ..."
    - echo "Docker push ..."
    - bash docker push vvalette/backend .
 - stage : "Package"
   before_script :
    - cd sample-application-frontend
   script :
    - echo "Docker build ..."
    - bash docker build -t vvalette/frontend .
    - echo "Docker login ..."
    - echo "Docker push ..."
    - bash docker push vvalette/backend .
    
cache :
 directories :
  - "$HOME/.m2/repository"
  - "$HOME/.npm"
  
services :
 - docker
