# tasks file for roles/backend
- name: Copy .env file
  copy:
    src: .env
    dest: /tmp/.env

- name: Run Backend
  docker_container:
    name: backend
    image: vvalette/backend
    networks:
      - name: app-network
    env_file: /tmp/.env
